### ISSUE TITLE
How do i fix this

### ISSUE THREAD

**Issue by CMDSKIDD** [Dominicentek/jupiter#1]
![Screenshot_20241128_212354_Termux](https://github.com/user-attachments/assets/66e2c71f-2a6a-4ef0-812e-7cab092c916d)

**Comment by fgetcat** [comment]
this is still very early development lmfao
its no different from regular sm64 aside from a demo imgui window to test that out
i dont work on this much since its not the biggest priority rn but i will when i have more time
